In [1]:
import pandas as pd

In [6]:
# 1st way to create a datafram 
info = {
    "Nmae":['adam','bob','eve'],
    "Age":[23,24,25],
    'cgpa':[7.8,8.9,9.5]
}

df = pd.DataFrame(info)

print(df)
print(df.index)
print(df.columns)

   Nmae  Age  cgpa
0  adam   23   7.8
1   bob   24   8.9
2   eve   25   9.5
RangeIndex(start=0, stop=3, step=1)
Index(['Nmae', 'Age', 'cgpa'], dtype='str')

In [11]:
# secound way to create a dataframe using lists of list 

df = pd.DataFrame([['adam',29,8.7],['jarry',21,8.6],['Rohit',25,6.9]] , columns = ['name','age','cgpa'])

df

    name  age  cgpa
0   adam   29   8.7
1  jarry   21   8.6
2  Rohit   25   6.9

In [12]:
# third way to create a dataframe is using numpy array

import numpy as np

np_arr =np.array([[1,2,3],[4,5,6]])

df = pd.DataFrame(np_arr , columns = ["A","B","C"])
df

   A  B  C
0  1  2  3
1  4  5  6