In [1]:
import pandas as pd

In [2]:
# Concatenation

df1 = pd.DataFrame({
    'id': [1,2,3],
    "name": ['adam','eiv','bob']
})


df2 = pd.DataFrame({
    'id': [4,5,6],
    "name": ['charlie','fester','gilian']
})

In [3]:
df1

   id  name
0   1  adam
1   2   eiv
2   3   bob

In [4]:
df2

   id     name
0   4  charlie
1   5   fester
2   6   gilian

In [6]:
pd.concat([df1,df2]) # Row based concationation
pd.concat([df1,df2], ignore_index = True) # Row based concationation

   id     name
0   1     adam
1   2      eiv
2   3      bob
3   4  charlie
4   5   fester
5   6   gilian